### ISSUE TITLE
/enchant add isn't actually implemented

### ISSUE THREAD

**Issue by VideoGameSmash12** [plexusorg/Module-TFMExtras#7]
The code for `/enchant` contains tab completion code for a nonexistent ability to add individual enchantments. This is confirmed by the fact that when you try to add an individual enchantment with the command, nothing happens.

https://github.com/plexusorg/Module-TFMExtras/blob/master/src/main/java/dev/plex/extras/command/EnchantCommand.java

**Comment by TheRedXD** [comment]
That's interesting, I might try to implement it a bit later, never worked with Plex, so would be fun to try
